### ISSUE TITLE
thrid issue

### ISSUE THREAD

**Issue by k7markn** [k7markn/react-issue-gantt#4]
```yaml
start_date: 2021/11/10
due_date: 2021/11/10
progress: 0.1
parent: 2
```
